create table users (
	id serial primary key,
	contributors_enabled boolean null,
	created_at character(250) null,
	default_profile boolean null,
	default_profile_image character(250) null,
	description character(250) null,
	favourites_count bigint null,
	follow_request_sent boolean null,
	following boolean null,
	followers_count bigint null,
	friends_count bigint null,
	geo_enabled boolean null,
	id_user bigint unique,
	id_str character(30) null,
	is_translator boolean null,
	lang character(3) null,
	listed_count bigint null,
	location character(250) null,
	name character(250),
	notifications boolean null,
	profile_background_color character(250) null,
	profile_background_image_url character(250) null,
	profile_background_image_url_https character(250) null,
	profile_background_tile boolean null,
	profile_banner_url character(250) null,
	profile_image_url character(250) null,
	profile_image_url_https character(250) null,
	profile_link_color character(250) null,
	profile_sidebar_border_color character(250) null,
	profile_sidebar_fill_color character(250) null,
	profile_text_color character(250) null,
	profile_use_background_image boolean null,
	protected boolean null,
	screen_name character(250),
	show_all_inline_media boolean null,
	statuses_count bigint null,
	time_zone character(250) null,
	url character(250) null,
	utc_offset bigint null,
	verified boolean null,
	withheld_in_countries character(250) null,
	withheld_scope character(250) null
);

create index on users (created_at);
create index on users (screen_name);
