create table users (
	id integer auto_increment primary key,
	contributors_enabled boolean null,
	created_at varchar(250) null,
	default_profile boolean null,
	default_profile_image varchar(250) null,
	description varchar(250) null,
	favourites_count bigint null,
	follow_request_sent boolean null,
	following boolean null,
	followers_count bigint null,
	friends_count bigint null,
	geo_enabled boolean null,
	id_user bigint,
	id_str varchar(30) null,
	is_translator boolean null,
	lang varchar(3) null,
	listed_count bigint null,
	location varchar(250) null,
	name varchar(250),
	notifications boolean null,
	profile_background_color varchar(250) null,
	profile_background_image_url varchar(250) null,
	profile_background_image_url_https varchar(250) null,
	profile_background_tile boolean null,
	profile_banner_url varchar(250) null,
	profile_image_url varchar(250) null,
	profile_image_url_https varchar(250) null,
	profile_link_color varchar(250) null,
	profile_sidebar_border_color varchar(250) null,
	profile_sidebar_fill_color varchar(250) null,
	profile_text_color varchar(250) null,
	profile_use_background_image boolean null,
	protected boolean null,
	screen_name varchar(250),
	show_all_inline_media boolean null,
	statuses_count bigint null,
	time_zone varchar(250) null,
	url varchar(250) null,
	utc_offset bigint null,
	verified boolean null,
	withheld_in_countries varchar(250) null,
	withheld_scope varchar(250) null
);


